name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn
    - name: Create build
      run: yarn run build
    - name: Deploy build files to gh-pages
      run: yarn run gh-pages
